# Generated by Django 3.0.10 on 2023-09-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
